services:
  - type: web
    name: ocr-unified
    env: docker
    plan: starter
    region: oregon
    # IMPORTANT: dockerfilePath is relative to rootDir
    rootDir: services/ocr-unified
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false
      - key: OCR_LANG
        value: en
