# Render Blueprint for OCR & Extraction Services
# Deploys two microservices for instant receipt processing

services:
  - type: web
    name: ocr-service
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: services/ocr/Dockerfile
    dockerContext: services/ocr
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: OCR_LANG
        value: en
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false

  - type: web
    name: extract-service
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: services/extract/Dockerfile
    dockerContext: services/extract
    healthCheckPath: /health
    autoDeploy: true
