# Render Blueprint for Unified OCR Service
# Single microservice for instant receipt processing (OCR + extraction)

services:
  - type: web
    name: ocr-unified
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: services/ocr-unified/Dockerfile
    dockerContext: services/ocr-unified
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: OCR_LANG
        value: en
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false
