# Render Blueprint for Unified OCR Service
# Single microservice: OCR + Extraction in one container ($7/month)

services:
  - type: web
    name: ocr-unified
    env: docker
    plan: starter
    region: oregon
    rootDir: services/ocr-unified
    dockerfilePath: services/ocr-unified/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false
      - key: OCR_LANG
        value: en
